// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type Task struct {
	TaskID      int32
	Title       string
	Description sql.NullString
}

type User struct {
	UserID                  int32
	EncryptedPassportSeries string
	EncryptedPassportNumber string
	Surname                 string
	Name                    string
	Patronymic              sql.NullString
	Address                 sql.NullString
}

type Worklog struct {
	WorklogID  int32
	UserID     int32
	TaskID     int32
	StartTime  time.Time
	EndTime    sql.NullTime
	HoursSpent sql.NullInt64
}
