// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	UserID         int32
	PassportSeries string
	PassportNumber string
	Surname        string
	Name           string
	Patronymic     pgtype.Text
	Address        pgtype.Text
}

type Worklog struct {
	WorklogID   int32           `json:"worklog_id"`
	UserID      int32           `json:"user_id"`
	Title       string          `json:"title"`
	Description pgtype.Text     `json:"description"`
	StartTime   pgtype.Timestamp `json:"start_time"`
	EndTime     pgtype.Timestamp `json:"end_time"`
	HoursSpent  pgtype.Text     `json:"hours_spent"`
}