// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type User struct {
	UserID         int32
	PassportSeries string
	PassportNumber string
	Surname        string
	Name           string
	Patronymic     sql.NullString
	Address        sql.NullString
}

type Worklog struct {
	WorklogID   int32
	UserID      int32
	Title       string
	Description sql.NullString
	StartTime   time.Time
	EndTime     sql.NullTime
	HoursSpent  sql.NullString
}
